server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: measurement-service
          uri: lb://measurement-service
          predicates:
            - Path=/api/quantity-measurements/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**,/oauth2/**,/login/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}