spring.application.name=quantity-measurement-app

server.port=8080

# =========================
# H2 DATABASE
# =========================

spring.datasource.url=jdbc:h2:mem:quantity_measurement;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# H2 CONSOLE
# =========================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# ACTUATOR
# =========================

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# =========================
# SWAGGER / OPENAPI
# =========================

springdoc.swagger-ui.path=/swagger-ui.html


# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email

